name: acc3

ta_select_keys:
  - acc_v3
obs_keys:
  - null

mainchart_keys:
  - null

subchart_keys:
  - dash@pos
  # - rlf_ma240_60@slope
  # - rlf_ma240_60@intercept
  # - rlf_ma240_60@r2
  # - rlf_ma240_60@t
