name: oracle

ta_select_keys:
  - null
buy_dates:
  - 1992-01-03 
  - 2003-08-28
  - 2009-08-05
  - 2020-04-07

sell_dates:
  - 2001-07-26
  - 2008-01-10
  - 2020-02-26



mainchart_keys:
  - ma240@value

subchart_keys:
  - dash@pos
  # - rlf_ma240_60@slope
  # - rlf_ma240_60@intercept
  # - rlf_ma240_60@r2
  # - rlf_ma240_60@t
  - rlf_ma240_60@slope_pct_annual