name: rlf

ta_select_keys:
  - ma240
  - rlf_ma240_60
obs_keys:
  - null

mainchart_keys:
  - ma240@value

subchart_keys:
  - dash@pos
  # - rlf_ma240_60@slope
  # - rlf_ma240_60@intercept
  # - rlf_ma240_60@r2
  # - rlf_ma240_60@t
  - rlf_ma240_60@slope_pct_annual