name: trend_momentum

ta_select_keys:
  - rsi_standard

obs_keys:
  - rsi_standard@ema_diff_norm
  - rsi_standard@mom_5
  - rsi_standard@mom_15
  - dash@pos

mainchart_keys:
  - ma60@value

subchart_keys:
  - dash@pos
  - dash@cash
  - dash@balance
  - dash@pnl