defaults:
  - mode: vis
  - ta@ta_ma: ma
  - ta@ta_ema: ema
  - ta@ta_rlf: rlf
  - data: yf
  - policy: dummy
  - env: paper_trade 
  - gui: lightweight_charts 

general:
  proxy: http://127.0.0.1:7897
  use_cache: false
  cache_dir: /tmp/gym_trade

